language: node_js
node_js:
- lts/boron
- node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: LJ+TIioi0LKXEhIVtXelEkd9VEpjhE08TJoqQbZXdevXKfTvteD3/ia9aFm2MXAxY+/bIiZz/165KzwgdnYQ9Wv8EUCVzmpR+Aifs9xJxMpZ+6qLgH6ZoGFiwL8sCDzyyBpQEnyI4VCgK3v2PWBAH6f2Yk4XLnZ4ZPA+8yvH82sSzwxSciWdCC7xV9JMrlMacHiXYp5XbtIwrhgZWCc3xrPt7VeDVPFJYgfVDBRf8hozZG3n3b2+iqENkd8iNVIzM5s5uXRP+Wnc9IYo7s0KsO/PaTUPJrPenhHcZcC6qbo5j4d4wMgxi+eCmVIvCyU6WdKZ5QydtolePqT/OQk9BNPUtTPvKR5SXIywMtx/lDDFv/vOIDPidfWICNen23T92FzbUhV6Ja1DuhL1BjUu0d4Nhpf1u72Fac1ZGUUrBgK8p9Ir7cDshlrfweUvgHmHsOuWqL4jzsYqB+P06YjytGwwQOK/dNfbH8SHZOOEpcapIXzb+9Uy1f6nEeIxrcCfSxrOkI5MVXyNlPdxOj8xI6deDI5KQnSpFEM6d7dbaPCcGF6OWyicprf9ZbXT9/7lbr4oFDMI1LnGeHRouu6px1eyfN6X082LiL8t1sy7w58shKT1dv/8HbjX7qyr1NMDz8h/B7bURFB/JtnVok5euycZhY1qXus7g8ZFO7Wrltg=
  file:
    - "remark-license.js"
    - "remark-license.min.js"
  on:
    tags: true
