language: node_js
node_js:
- lts/boron
- node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: X9hKBe+4FZrDT8BV0rpMlffy7VW+xi7Z9pfpW5etNSx+6Q/RK58kwfMDvlx2cXBCQ/zGGPzQIDxOr3UUoQiyb6d1HXubkNjKpBgU82J149CZaMQ/H91DYsHf03lPj1WLSNfHFs+DhbcsJHDmYJz6LUrc+ZH3nUxT236Djor/0Hu57U37hrYSyiK0YArtzB8MFzoVvVQlemGjunGDPFcz0z0xwo9Emk5d0S0XGhq3yQVy/yjAGMl+Eqiers9fc8gFDi50edGhqZKsHz5ZrEnCsVRXElsZNvVmhppRinUSgB9By/H01WQ+ASM0Uy+kwAHoCXKIl3tderkXC1kFlAsBjShe+mq3AHFVcS2Pub9D9Job49SqCFOfQj0atYsWnxQFjLjkvPeNHr9YiuZXu1VRsF1AvRMqotZ8Q3b8H1UMLEuWWiKBDl9G6FPGIhQ63Dlul+mVeB5jUeck23r6XMu3+/0g32jTqQ8f22JI7tCdQC4vKypfiecqeoQ6cP6xGGx5piBt6HPzEqVF9iAgU+gfCDHO2XN59PolNlmENIUdESLykyuJmsKlO++BxZizczKTacmOiI6pKOVMjkI0yHpeL4gYDOvCx/1AomagCfyTcD6A5tvD9N3ReoJGsSEBp9/27HFeeoIjbcBmf/qNBwVzHUK7pAbPO7qtfSfa9oDbDuc=
  file:
    - "remark-license.js"
    - "remark-license.min.js"
  on:
    tags: true
